version: '3.8'

services:
  # Наш веб-сервер Nginx
  my-custom-web:
    image: nginx:latest
    container_name: my-custom-web
    ports:
      _ "8080:80"
    volumes:
      _ ./html:/usr/share/nginx/html
    depends_on:
      - db  # Наш веб-сервер будет запускаться только ПОСЛЕ того, как поднимется база

  # Наша новая база данных PostgreSQL
  db:
    image: postgres:15
    container_name: my-postgres-db
    restart: always
    environment:
      POSTGRES_USER: dmitriy
      POSTGRES_PASSWORD: ${DB_PASSWORD}  # Пароль прилетит сюда из переменных окружения
      POSTGRES_DB: my_cool_database
    ports:
      - "5432:5432"
  volumes:
    - pgdata:/var/lib/postgresql/data  # Магия сохранения данных!

# Объявляем постоянный диск (volume) для базы данных
volumes:
  pgdata:
