version: '3.8'

services:
  my-custom-web:
    image: nginx:latest
    container_name: my-custom-web
    ports:
      - "8080:80"
    volumes:
      - ./html:/usr/share/nginx/html
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: my-postgres-db
    restart: always
    environment:
      POSTGRES_USER: dmitriy
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: my_cool_database
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
# Forse trigger
