name: Deploy Docker Compose Project

on:
  push:
    branches: [ "main" ]

jobs:
  deploy-to-server:
    runs-on: self-hosted  # <--- Ключевая магия! Говорим запускать это НА ТВОЕМ сервере
    steps:
      - name: Pull code from GitHub
        uses: actions/checkout@v4  # Робот сам скачает свежий код из репозитория на сервер

      - name: Restart Docker Compose
        env:
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }} # Берем секрет из GitHub и прокидываем в систему
        run: |
          docker compose down
          docker compose up -d
